name: Update LeetCode Stats

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 8 * * *' 

jobs:
  update-readme:
    name: Update LeetCode Stats Card
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: j-Rass/leetcode-stats-card-action@main
        with:
          leetcode_username: fonsecadesouzamanoel
